import type { Metadata } from "next";
import { Inter } from "next/font/google";
import styles from "./layout.module.scss"
import Image from 'next/image';
import { SideBar } from "@/app/components/SideBar/SideBar";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <SideBar />
      <div className={styles.containerWrapper}>
        <div className={styles.header}>
          <Image
            src={`/icons/profileIcon.svg`}
            alt="musician image"
            width={46}
            height={46}
          />
        </div>
        {children}
      </div>
    </>
  );
}
